title: "Medical Named Entity Recognition"
description: "This project uses Pubtator data to re-create my own medical NER model"
vars:
  config: "config.cfg"
  name: "medical-named-entity-recognition"
  version: "0.0.0"
  train: "0to999"
  eval: "1000to1999"
directories: [ "assets", "training", "configs", "scripts", "corpus", "packages" ]
workflows:
  all:
    - "download_data"
    - "preprocess"
    - "train"
    - "evaluate"
commands:
  - name: "download_data"
    help: "Download data from pubtator"
    script:
      - "python scripts/download_data.py --last-id 10000"
    deps:
      - "scripts/download_data.py"
    outputs:
      - "data/raw/pubtator/from1to10000.jsonl"

  - name: "preprocess"
    help: "Convert the data to spaCy's binary format"
    script:
      - "python scripts/preprocess.py data/raw/pubtator/from1to10000.jsonl"
    deps:
      - "data/raw/pubtator/from1to10000.jsonl"
      - "scripts/preprocess.py"
    outputs:
      - "corpus/train.spacy"
      - "corpus/eval.spacy"

  - name: "train"
    help: "Train a named entity recognition model"
    script:
      - "python -m spacy train configs/${vars.config} --output training/ --paths.train corpus/train.spacy --paths.dev corpus/eval.spacy --paths.vectors en_core_web_md"
    deps:
      - "corpus/train.spacy"
      - "corpus/eval.spacy"
    outputs:
      - "training/model-best"

  - name: "evaluate"
    help: "Evaluate the model and export metrics"
    script:
      - "python -m spacy evaluate training/model-best corpus/${vars.eval}.spacy --output training/metrics.json"
    deps:
      - "corpus/${vars.eval}.spacy"
      - "training/model-best"
    outputs:
      - "training/metrics.json"

  - name: "package"
    help: "Package the trained model so it can be installed"
    script:
      - "python -m spacy package training/model-best packages --name ${vars.name} --version ${vars.version} --force"
    deps:
      - "training/model-best"
    outputs_no_cache:
      - "packages/en_${vars.name}-${vars.version}/dist/en_${vars.name}-${vars.version}.tar.gz"

  - name: "visualize-model"
    help: "Visualize the model's output interactively using Streamlit"
    script:
      - "streamlit run scripts/visualize_model.py training/model-best \"He was prescribed Aspirin.\""
    deps:
      - "scripts/visualize_model.py"
      - "training/model-best"

  - name: "visualize-data"
    help: "Explore the annotated data in an interactive Streamlit app"
    script:
      - "streamlit run scripts/visualize_data.py assets/${vars.train}.jsonl,assets/${vars.eval}.jsonl"
    deps:
      - "scripts/visualize_data.py"
      - "assets/${vars.train}.jsonl"
      - "assets/${vars.eval}.jsonl"
