# datamodel-codegen --input ./data/test/raw/dummy.json --input-file-type json \
#    --class-name Pubtator --enable-faux-immutability > scripts/pubtator_pydantic.py

# generated by datamodel-codegen:
#   filename:  dummy.json
#   timestamp: 2021-08-29T12:53:33+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Infons(BaseModel):
    class Config:
        allow_mutation = False

    type: str


class Location(BaseModel):
    class Config:
        allow_mutation = False

    offset: int
    length: int


class Annotation(BaseModel):
    class Config:
        allow_mutation = False

    infons: Infons
    text: str
    locations: List[Location]


class Passage(BaseModel):
    class Config:
        allow_mutation = False

    offset: int
    text: str
    annotations: List[Annotation]


class Pubtator(BaseModel):
    class Config:
        allow_mutation = False

    id: str
    passages: List[Passage]
